spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/codingdojo
    username: codingdojo
    password: codingdojo
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    org.liquibase: INFO
