spring:
  datasource:
    url: jdbc:tc:postgresql:///codingdojo
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
